# Generated by Django 3.0.8 on 2020-07-18 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnroleCoueses',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=50)),
                ('fac', models.CharField(max_length=50)),
                ('dat', models.DateField(default=datetime.date(2020, 1, 1))),
                ('timing', models.TimeField(default=datetime.time(2, 30, 5))),
                ('stdname', models.CharField(max_length=50)),
                ('std_cont', models.IntegerField(unique=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleNewClass',
            fields=[
                ('regn', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50, unique=True)),
                ('Faculty', models.CharField(max_length=50)),
                ('Date', models.DateField(default=datetime.date(2020, 1, 1))),
                ('Time', models.TimeField(default=datetime.time(2, 30, 5))),
                ('Fee', models.FloatField(max_length=90000)),
                ('Duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('regno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('user', models.CharField(max_length=50, unique=True)),
                ('pas', models.CharField(max_length=50)),
            ],
        ),
    ]
