# Generated by Django 3.0.8 on 2020-07-19 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolecoueses',
            old_name='course',
            new_name='Course_Name',
        ),
        migrations.RenameField(
            model_name='enrolecoueses',
            old_name='status',
            new_name='Enroll_status',
        ),
        migrations.RenameField(
            model_name='enrolecoueses',
            old_name='fac',
            new_name='Faculty_Name',
        ),
        migrations.RenameField(
            model_name='enrolecoueses',
            old_name='no',
            new_name='Register_No',
        ),
        migrations.RenameField(
            model_name='enrolecoueses',
            old_name='std_cont',
            new_name='Student_Contact',
        ),
        migrations.RenameField(
            model_name='enrolecoueses',
            old_name='stdname',
            new_name='Student_Name',
        ),
        migrations.RenameField(
            model_name='enrolecoueses',
            old_name='dat',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='enrolecoueses',
            name='timing',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
